### ISSUE TITLE
Not Working !

### ISSUE THREAD

**Issue by AmrAbdeen** [mohamedzebib/apex_plugin_google_captcha_v2#1]
First Thank you Mohamed,
Now i tested your plugin @ login page for APEX 5.1.
Then i found that:

- In all cases [Clicked on re-captcha or not clicked ] i can login to my app.
- Now i created [Site key, Secret key] and inserted them to plugin setting.
- ACL configured.
- Insted of https:// i created reverse proxy for that by my host provider "MaxApex.com".

My problem is: reCAPTCHA not working with login process.
I think .. if i not clicked on reCAPTCH that i can't login to my app, whats wrong ..?

Regards,
Amr

**Comment by mohamedzebib** [comment]
Hi Amr,

You are right. It seems the plugin is not compatible with the 5.1 version of Apex.
Thanks for the feedback. I will investigate the problem. Will keep you posted.

Regards.
Mohamed.

**Comment by cboillat** [comment]
Hi @mohamedzebib,

Any news concerning this issue raised by Amr ?
I would really appreciate an update that fix the APEX 5.1 problem.

Tell us if we can help in any way.

Regards
Clément

**Comment by mohamedzebib** [comment]
Hi Clement,

Sorry, I did not have time to resolve the issue. In 5.1 the plugin render function was changed from a function to a procedure. This part needs to be rewritten.

Regards.
Mohamed.

**Comment by McRange** [comment]
Hi,
I've invested some time to find the bug:
In APEX 5.1, the validation procedure of an item plugin is only called if there is an element in the DOM that has exactly the same ID as `p_result.navigable_dom_id` of the rendering procedure. If this is NULL, it must be identical to the item name. In APEX 5. In APEX 5.0 it was always executed, even if this condition was not fulfilled.

So just set 
    `HTP.P( '<div id="' || P_ITEM.NAME || '"></div>' );`
in the rendering function / procedure to get it running.
I added my version of the plugin. This uses API version 2 and includes some minor changes (e. g. SQL query for keys and wallet).
[item_type_plugin_ais_google_recaptcha_v2.zip](https://github.com/mohamedzebib/apex_plugin_google_captcha_v2/files/1563310/item_type_plugin_ais_google_recaptcha_v2.zip)

**Comment by mohamedzebib** [comment]
Hi McRange,

Good catch. Thanks.

I could not completely test it since apex.oracle.com would not let me make an https call. But for sure, you cannot login if you do select the reCaptcha in APEX 5.1.

Here is an updated version of the my plugin for those who already integrated it.
Please, let me know if it works for you. When I have time, I will post a complete updated version.

[apex_plugin_google_captcha_v2.txt](https://github.com/mohamedzebib/apex_plugin_google_captcha_v2/files/1564539/apex_plugin_google_captcha_v2.txt)

**Comment by mohamedzebib** [comment]
Hi Clement,

The real reason it was not working, is that APEX was creating a div with the same item_name item_name+_RECAPTCHA_CONTAINER which was creating a conflict. If you remove _RECAPTCHA_CONTAINER or append anything else than _RECAPTCHA_CONTAINER to the item_name, it works fine.

Thanks anyway for pointing out to that issue. I am sure it will help a lot of people who are using this plugin.

Best Regards.
Mohamed.
